[package]
name = "store"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
env_logger = "0.9.0"

futures = "*"

chrono = "0.4.19"
ring = "0.16.20"

serde = "1.0.139"
serde_json = "1.0.82"

evmap = "10.0.2"
rayon = "1.5.3"

zip = "0.6.2"
walkdir = "2.3.2"